### ISSUE TITLE
[TEST ISSUE] Epic

### ISSUE THREAD

**Issue by maxim-lobanov** [maxim-lobanov/build-issue-dependencies-graph#1]
# Epic 1

## Spec

- [ ] https://github.com/maxim-lobanov/build-issue-dependencies-graph/issues/2
- [ ] https://github.com/maxim-lobanov/build-issue-dependencies-graph/issues/3
- [ ] https://github.com/maxim-lobanov/build-issue-dependencies-graph/issues/4
- [ ] https://github.com/maxim-lobanov/build-issue-dependencies-graph/issues/5
- [ ] https://github.com/maxim-lobanov/build-issue-dependencies-graph/issues/6
- [ ] https://github.com/maxim-lobanov/build-issue-dependencies-graph/issues/7
- [ ] https://github.com/maxim-lobanov/build-issue-dependencies-graph/issues/8

### Spec Diagram

```mermaid
flowchart TD

%% <Legend>
legend --> start
subgraph legend["Legend"]
    direction LR;
    notstarted("Issue is not started"):::notstarted;
    started("Issue is in progress"):::started;
    completed("Issue is done"):::completed;
    notstarted --> started --> completed;
end

%% </Legend>


%% <CSS>

classDef notstarted fill:#FFF,color:#000;
classDef started fill:#fae17d,color:#000;
classDef completed fill:#ccffd8,color:#000;

%% </CSS>


%% <Issues>

start("Start"):::default;

issue1488484564("[TEST ISSUE] Child issue 1"):::completed;

issue1488484695("[TEST ISSUE] Child issue 2"):::completed;

issue1488484833("[TEST ISSUE] Child issue 3"):::completed;

issue1524488391("[TEST ISSUE] Child issue 4"):::completed;

issue1524488450("[TEST ISSUE] Child issue 5"):::completed;

issue1524488472("[TEST ISSUE] Child issue 6"):::notstarted;

issue1524488513("[TEST ISSUE] Child issue 7"):::notstarted;

finish("Finish"):::default;

%% </Issues>


%% <Dependencies>

start --> issue1488484564;
start --> issue1488484695;
start --> issue1524488391;
start --> issue1524488450;
issue1488484564 --> issue1488484833;
issue1488484695 --> issue1488484833;
issue1488484833 --> issue1524488472;
issue1524488450 --> issue1524488472;
issue1524488450 --> issue1524488513;
issue1524488391 --> finish;
issue1524488472 --> finish;
issue1524488513 --> finish;

%% </Dependencies>

```

### Hello
Test content 1
